export const GET_RECORDS = "GET_RECORDS";
export const GET_LAST_RESULTS = "GET_LAST_RESULTS";
export const GET_BODY_MEASUREMENTS = "GET_BODY_MEASUREMENTS";
export const GET_TRAININGS = "GET_TRAININGS";